# Generated by Django 4.2.7 on 2024-02-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
