# Generated by Django 4.2.7 on 2024-03-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
