# Generated by Django 4.2.7 on 2024-03-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('guidance', 'Guidance'), ('admin', 'Admin')], default='student', max_length=20, verbose_name='Role'),
        ),
    ]
