# Generated by Django 4.2.7 on 2024-03-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='border_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
