# Generated by Django 4.2.7 on 2024-03-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_remove_event_creator_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
